Update pr_template_verifier.yml

diff --git a/.github/workflows/pr_template_verifier.yml b/.github/workflows/pr_template_verifier.yml
--- a/.github/workflows/pr_template_verifier.yml
+++ b/.github/workflows/pr_template_verifier.yml
@@ -1,4 +1,4 @@
-name: PR Template Checker
+name: PR Template Verifier
 
 on:
   pull_request:
@@ -14,37 +14,33 @@ jobs:
       - name: Verify PR template
         run: |
           PR_BODY=$(tr -d '\r' < $GITHUB_EVENT_PATH | jq -r '.pull_request.body')
-          if [[ ! $PR_BODY =~ "## Description" || ! $PR_BODY =~ "## Type of change" || ! $PR_BODY =~ "## How Has This Been Tested?" || ! $PR_BODY =~ "## Checklist:" || ! $PR_BODY =~ "Fixes #[0-9]+" ]]; then
-            echo "One or more sections of the PR template are missing!"
-            exit 1
+          
+          # Check if description section is present and contains description
+          if [[ ! $PR_BODY =~ "## Description" || $(echo "$PR_BODY" | grep -c "## Description") -ne 1 ]]; then
+              echo "Description section is missing or duplicated!"
+              exit 1
           fi
 
-          # Check if description is present
-          if [[ $(echo "$PR_BODY" | grep -c "## Description") -ne 1 ]]; then
-            echo "Description section is missing or duplicated!"
-            exit 1
+          # Check if type of change section is present and at least one option is marked
+          if [[ ! $PR_BODY =~ "## Type of change" || $(echo "$PR_BODY" | grep -c "\[x\]") -eq 0 ]]; then
+              echo "At least one option should be marked in 'Type of change' section!"
+              exit 1
           fi
 
-          # Check if type of change is present
-          if [[ $(echo "$PR_BODY" | grep -c "## Type of change") -ne 1 ]]; then
-            echo "Type of change section is missing or duplicated!"
-            exit 1
+          # Check if How Has This Been Tested? section is present and either some description or test options are marked
+          if [[ ! $PR_BODY =~ "## How Has This Been Tested?" || $(echo "$PR_BODY" | grep -c "\[x\]") -eq 0 ]]; then
+              echo "Either some description or at least one test option should be marked in 'How Has This Been Tested?' section!"
+              exit 1
           fi
 
-          # Check if How Has This Been Tested? section is present
-          if [[ $(echo "$PR_BODY" | grep -c "## How Has This Been Tested?") -ne 1 ]]; then
-            echo "How Has This Been Tested? section is missing or duplicated!"
-            exit 1
-          fi
-
-          # Check if Checklist section is present
-          if [[ $(echo "$PR_BODY" | grep -c "## Checklist:") -ne 1 ]]; then
-            echo "Checklist section is missing or duplicated!"
-            exit 1
+          # Check if Checklist section is present and at least one option is marked
+          if [[ ! $PR_BODY =~ "## Checklist:" || $(echo "$PR_BODY" | grep -c "\[x\]") -eq 0 ]]; then
+              echo "At least one option should be marked in the checklist!"
+              exit 1
           fi
 
           # Check if Fixes #(issue) is present
-          if [[ $(echo "$PR_BODY" | grep -c "Fixes #[0-9]+") -ne 1 ]]; then
-            echo "Fixes #(issue) is missing or duplicated!"
-            exit 1
+          if [[ ! $PR_BODY =~ "Fixes #[0-9]+" ]]; then
+              echo "Fixes #(issue) is missing!"
+              exit 1
           fi
